{
  "schema_version": "1.2.0",
  "id": "GHSA-7372-q459-jxhr",
  "modified": "2022-05-17T01:27:07Z",
  "published": "2022-05-17T01:27:07Z",
  "aliases": [
    "CVE-2014-1624"
  ],
  "details": "Race condition in the xdg.BaseDirectory.get_runtime_dir function in python-xdg 0.25 allows local users to overwrite arbitrary files by pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the get_runtime_dir function is called.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-1624"
    },
    {
      "type": "WEB",
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/90618"
    },
    {
      "type": "WEB",
      "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=736247"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2014/01/21/3"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2014/01/21/4"
    },
    {
      "type": "WEB",
      "url": "http://www.securityfocus.com/bid/65042"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-59"
    ],
    "severity": "LOW",
    "github_reviewed": false
  }
}