{
  "schema_version": "1.4.0",
  "id": "GHSA-f4g4-cj8f-3cr9",
  "modified": "2022-05-14T03:53:47Z",
  "published": "2022-05-14T03:53:47Z",
  "aliases": [
    "CVE-2017-7214"
  ],
  "details": "An issue was discovered in exception_wrapper.py in OpenStack Nova 13.x through 13.1.3, 14.x through 14.0.4, and 15.x through 15.0.1. Legacy notification exception contexts appearing in ERROR level logs may include sensitive information such as account passwords and authorization tokens.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-7214"
    },
    {
      "type": "WEB",
      "url": "https://access.redhat.com/errata/RHSA-2017:1508"
    },
    {
      "type": "WEB",
      "url": "https://access.redhat.com/errata/RHSA-2017:1595"
    },
    {
      "type": "WEB",
      "url": "https://launchpad.net/bugs/1673569"
    },
    {
      "type": "WEB",
      "url": "http://www.securityfocus.com/bid/96998"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-532"
    ],
    "severity": "CRITICAL",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2017-03-21T18:59:00Z"
  }
}