{
  "schema_version": "1.2.0",
  "id": "GHSA-6x94-2xr2-xgw3",
  "modified": "2022-09-11T00:09:39Z",
  "published": "2022-05-24T22:00:28Z",
  "aliases": [
    "CVE-2019-12105"
  ],
  "summary": "",
  "details": "In supervisord in Supervisor through 4.0.2, an unauthenticated user can read log files or restart a service. WARNING: This issue will not be fixed by the maintainer. The ability to run an open server will not be removed because users often use it for local development, therefore no action will be taken.",
  "severity": [

  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "supervisor"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4.0.3"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 4.0.2"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-12105"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Supervisor/supervisor/issues/1245"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Supervisor/supervisor/commit/4e334d9cf2a1daff685893e35e72398437df3dcb"
    },
    {
      "type": "WEB",
      "url": "http://supervisord.org/configuration.html#supervisorctl-section-settings"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "MODERATE",
    "github_reviewed": false
  }
}