{
  "schema_version": "1.3.0",
  "id": "GHSA-rprw-h62v-c2w7",
  "modified": "2022-11-27T21:17:56Z",
  "published": "2019-01-04T17:45:26Z",
  "aliases": [
    "CVE-2017-18342"
  ],
  "summary": "\"AnT1nG\"PyYAML insecurely deserializes YAML strings leading to arbitrary code execution",
  "details": "[In](https://github.com/AnT1nG82) (https://g.dev/AnT1nG)\nPyYAML before 4.1, the yaml.load() API could exe\n![FB_IMG_1668241262904](https://user-images.githubusercontent.com/104885716/204160071-64b1ff1e-6761-452e-aeae-8fe2cf4d964d.jpg)\ncute arbitrary code. In other words, yaml.safe_load is not used.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pyyaml"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4.1"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-18342"
    },
    {
      "type": "WEB",
      "url": "https://github.com/marshmallow-code/apispec/issues/278"
    },
    {
      "type": "WEB",
      "url": "https://github.com/yaml/pyyaml/issues/193"
    },
    {
      "type": "WEB",
      "url": "https://github.com/yaml/pyyaml/pull/74"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/yaml/pyyaml"
    },
    {
      "type": "WEB",
      "url": "https://github.com/yaml/pyyaml/blob/master/CHANGES"
    },
    {
      "type": "WEB",
      "url": "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JEX7IPV5P2QJITAMA5Z63GQCZA5I6NVZ/"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KSQQMRUQSXBSUXLCRD3TSZYQ7SEZRKCE/"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M6JCFGEIEOFMWWIXGHSELMKQDD4CV2BA/"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/202003-45"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-502"
    ],
    "severity": "HIGH",
    "github_reviewed": true
  }
}