{
  "schema_version": "1.2.0",
  "id": "GHSA-x33v-f3gp-gw2c",
  "modified": "2022-05-14T02:10:10Z",
  "published": "2022-05-14T02:10:10Z",
  "aliases": [
    "CVE-2013-2132"
  ],
  "details": "bson/_cbsonmodule.c in the mongo-python-driver (aka. pymongo) before 2.5.2, as used in MongoDB, allows context-dependent attackers to cause a denial of service (NULL pointer dereference and crash) via vectors related to decoding of an \"invalid DBRef.\"",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2013-2132"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mongodb/mongo-python-driver/commit/a060c15ef87e0f0e72974c7c0e57fe811bbd06a2"
    },
    {
      "type": "WEB",
      "url": "https://jira.mongodb.org/browse/PYTHON-532"
    },
    {
      "type": "WEB",
      "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=710597"
    },
    {
      "type": "WEB",
      "url": "http://lists.opensuse.org/opensuse-updates/2013-06/msg00180.html"
    },
    {
      "type": "WEB",
      "url": "http://seclists.org/oss-sec/2013/q2/447"
    },
    {
      "type": "WEB",
      "url": "http://ubuntu.com/usn/usn-1897-1"
    },
    {
      "type": "WEB",
      "url": "http://www.debian.org/security/2013/dsa-2705"
    },
    {
      "type": "WEB",
      "url": "http://www.osvdb.org/93804"
    },
    {
      "type": "WEB",
      "url": "http://www.securityfocus.com/bid/60252"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "MODERATE",
    "github_reviewed": false
  }
}