{
  "schema_version": "1.2.0",
  "id": "GHSA-9pv8-q5rx-c8gq",
  "modified": "2021-09-08T20:21:22Z",
  "published": "2018-07-13T15:16:59Z",
  "aliases": [
    "CVE-2017-16764"
  ],
  "summary": "Critical severity vulnerability that affects django_make_app",
  "details": "An exploitable vulnerability exists in the YAML parsing functionality in the read_yaml_file method in io_utils.py in django_make_app 0.1.3. A YAML parser can execute arbitrary Python commands resulting in command execution. An attacker can insert Python into loaded YAML to trigger this vulnerability.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django_make_app"
      },
      "versions": [
        "0.1.3"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-16764"
    },
    {
      "type": "WEB",
      "url": "https://github.com/illagrenan/django-make-app/issues/5"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-9pv8-q5rx-c8gq"
    },
    {
      "type": "WEB",
      "url": "https://joel-malwarebenchmark.github.io/blog/2017/11/12/cve-2017-16764-vulnerability-in-django-make-app/"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/illagrenan/django-make-app"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "CRITICAL",
    "github_reviewed": true
  }
}